#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SchoolManagement.Droid.Resource", IsApplication=true)]

namespace SchoolManagement.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.UserDialogs.Resource.Attribute.ahBarColor = global::SchoolManagement.Droid.Resource.Attribute.ahBarColor;
			global::Acr.UserDialogs.Resource.Attribute.ahBarLength = global::SchoolManagement.Droid.Resource.Attribute.ahBarLength;
			global::Acr.UserDialogs.Resource.Attribute.ahBarWidth = global::SchoolManagement.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahCircleColor = global::SchoolManagement.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.UserDialogs.Resource.Attribute.ahDelayMillis = global::SchoolManagement.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.UserDialogs.Resource.Attribute.ahRadius = global::SchoolManagement.Droid.Resource.Attribute.ahRadius;
			global::Acr.UserDialogs.Resource.Attribute.ahRimColor = global::SchoolManagement.Droid.Resource.Attribute.ahRimColor;
			global::Acr.UserDialogs.Resource.Attribute.ahRimWidth = global::SchoolManagement.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahSpinSpeed = global::SchoolManagement.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Attribute.ahText = global::SchoolManagement.Droid.Resource.Attribute.ahText;
			global::Acr.UserDialogs.Resource.Attribute.ahTextColor = global::SchoolManagement.Droid.Resource.Attribute.ahTextColor;
			global::Acr.UserDialogs.Resource.Attribute.ahTextSize = global::SchoolManagement.Droid.Resource.Attribute.ahTextSize;
			global::Acr.UserDialogs.Resource.Drawable.ic_errorstatus = global::SchoolManagement.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.UserDialogs.Resource.Drawable.ic_successstatus = global::SchoolManagement.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.UserDialogs.Resource.Drawable.roundedbg = global::SchoolManagement.Droid.Resource.Drawable.roundedbg;
			global::Acr.UserDialogs.Resource.Drawable.roundedbgdark = global::SchoolManagement.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.UserDialogs.Resource.Id.loadingImage = global::SchoolManagement.Droid.Resource.Id.loadingImage;
			global::Acr.UserDialogs.Resource.Id.loadingProgressBar = global::SchoolManagement.Droid.Resource.Id.loadingProgressBar;
			global::Acr.UserDialogs.Resource.Id.loadingProgressWheel = global::SchoolManagement.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.UserDialogs.Resource.Id.textViewStatus = global::SchoolManagement.Droid.Resource.Id.textViewStatus;
			global::Acr.UserDialogs.Resource.Layout.loading = global::SchoolManagement.Droid.Resource.Layout.loading;
			global::Acr.UserDialogs.Resource.Layout.loadingimage = global::SchoolManagement.Droid.Resource.Layout.loadingimage;
			global::Acr.UserDialogs.Resource.Layout.loadingprogress = global::SchoolManagement.Droid.Resource.Layout.loadingprogress;
			global::Acr.UserDialogs.Resource.String.ApplicationName = global::SchoolManagement.Droid.Resource.String.ApplicationName;
			global::Acr.UserDialogs.Resource.String.Hello = global::SchoolManagement.Droid.Resource.String.Hello;
			global::Acr.UserDialogs.Resource.String.library_name = global::SchoolManagement.Droid.Resource.String.library_name;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarLength = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarWidth = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahCircleColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahDelayMillis = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRadius = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimWidth = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahText = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextSize = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarColor = global::SchoolManagement.Droid.Resource.Attribute.ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarLength = global::SchoolManagement.Droid.Resource.Attribute.ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarWidth = global::SchoolManagement.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahCircleColor = global::SchoolManagement.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahDelayMillis = global::SchoolManagement.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRadius = global::SchoolManagement.Droid.Resource.Attribute.ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimColor = global::SchoolManagement.Droid.Resource.Attribute.ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimWidth = global::SchoolManagement.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahSpinSpeed = global::SchoolManagement.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahText = global::SchoolManagement.Droid.Resource.Attribute.ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextColor = global::SchoolManagement.Droid.Resource.Attribute.ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextSize = global::SchoolManagement.Droid.Resource.Attribute.ahTextSize;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::SchoolManagement.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::SchoolManagement.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbg = global::SchoolManagement.Droid.Resource.Drawable.roundedbg;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::SchoolManagement.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingImage = global::SchoolManagement.Droid.Resource.Id.loadingImage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::SchoolManagement.Droid.Resource.Id.loadingProgressBar;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::SchoolManagement.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.textViewStatus = global::SchoolManagement.Droid.Resource.Id.textViewStatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loading = global::SchoolManagement.Droid.Resource.Layout.loading;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingimage = global::SchoolManagement.Droid.Resource.Layout.loadingimage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingprogress = global::SchoolManagement.Droid.Resource.Layout.loadingprogress;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.ApplicationName = global::SchoolManagement.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.Hello = global::SchoolManagement.Droid.Resource.String.Hello;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.library_name = global::SchoolManagement.Droid.Resource.String.library_name;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarLength = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarWidth = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahCircleColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRadius = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimWidth = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahText = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextSize = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::SchoolManagement.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::SchoolManagement.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::SchoolManagement.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::SchoolManagement.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::SchoolManagement.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::SchoolManagement.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::SchoolManagement.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::SchoolManagement.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::SchoolManagement.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::SchoolManagement.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::SchoolManagement.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::SchoolManagement.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::SchoolManagement.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::SchoolManagement.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::SchoolManagement.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::SchoolManagement.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::SchoolManagement.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::SchoolManagement.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::SchoolManagement.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::SchoolManagement.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::SchoolManagement.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::SchoolManagement.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::SchoolManagement.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::SchoolManagement.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::SchoolManagement.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SchoolManagement.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SchoolManagement.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accounts = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ApplyLeave = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ApplyLeaveL = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrowleft = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arrowright = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ComplainBox = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ComplainBoxL = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int down_arrow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int EnterStudentMark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int EnterStudentMarkL = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int error = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ExamTimetable = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ExamTimetableL = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int FillUpAttendance = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int FillUpAttendanceL = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int home = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int HomeWork = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int HomeWorkL = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int HoweWork = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int HoweWorkL = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_errorstatus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_successstatus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int L3 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int L4 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int left_menu = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int line_menu = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int LogbookFillup = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int LogbookFillupL = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int LogOut = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int LogOutL = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int N3 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int N4 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Notification = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int NotificationL = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roundedbg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int roundedbgdark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int school = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int StudentBehaviourNotice = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int StudentBehaviourNoticeL = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int success = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int test = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int test23 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int TodaySchedule = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int TodayScheduleL = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int UploadSamplePaper = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int UploadSamplePaperL = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ViewActivityNotice = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ViewActivityNoticeL = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ViewAttendance = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ViewAttendanceL = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ViewAttendanceSummary = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ViewAttendanceSummaryL = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ViewComplain = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ViewComplainL = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ViewResult = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ViewResultL = 2130837561;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int loadingImage = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int loadingProgressBar = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int loadingProgressWheel = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int textViewStatus = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
